services:
  frontend:
    container_name: debug-puzzle-frontend
    working_dir: /app
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - "5174:5174"
    volumes:
      - node_modules:/app/node_modules
      - ./frontend:/app
    command: npm run dev

  backend:
    container_name: debug-puzzle-backend
    working_dir: /app
    build: 
      context: ./backend
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: python app.py

volumes:
  node_modules:


